<?php

/**
 * PluginPointExchangeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPointExchangeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPointExchangeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPointExchange');
    }
}