<?php

/**
 * PluginPointSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPointSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPointSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPointSetting');
    }
}